[profile.default]
src = "src"
out = "out"
build_info = true
ffi = false
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
